Add support for cgroups, ct and packet marks, and setting packet metainformation
mullvad/nftnl-rs pull request #24
Opened 2020-02-25 15:20 UTC by dlon

Changes:
* Add expressions `&nft_expr!(meta cgroup)` and `&nft_expr!(meta mark)`
* Set immediate data: `&nft_expr!(immediate data 1234)`
* Set packet metadata, e.g. `&nft_expr!(meta mark set)` (preceded by `immediate ...`)
* Support ct/connection marks: `&nft_expr!(ct mark)` and `&nft_expr!(ct mark set)`.

2020-02-26 09:12 UTC, faern requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/24)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @dlon and @faern)

___
*[nftnl/src/expr/ct.rs, line 16 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-fd4rBWkISRbJy9HB:-M1-fd4rBWkISRbJy9HC:b-vntjpu) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/ct.rs#L16)):*
> ```Rust
> 
> pub enum Conntrack {
>     Mark,
> ```

Same feedback as on the `Meta` type. Can't we make the enum carry the `set_value` only in the variants where it makes sense? That is if only setting a value makes sense in a subset of the variants. If it's always valid to `set_value: true` my argument does not hold, but if so I think we should work on the structure here to make the wrapper `ConntrackStruct` the top level type and better named and have the variant be a sub-type.
___
*[nftnl/src/expr/immediate.rs, line 6 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-h73p5eH5Bz4Crxpt:-M1-h73p5eH5Bz4Crxpu:b-o9q2zp) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/immediate.rs#L6)):*
> ```Rust
> use std::mem::size_of_val;
> 
> /// An immediate expression.
> ```

Since on the `libnftnl` level a verdict is an immediate expression users might come to this module/type to find out how to do verdicts. If we keep them as separate types I think the documentation for the `Immediate` should say this and point to the docs for the `Verdict` type.
___
*[nftnl/src/expr/meta.rs, line 33 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-fCbX6boABwNGroR1:-M1-fCbX6boABwNGroR2:bwpiwnm) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/meta.rs#L33)):*
> ```Rust
> }
> 
> pub struct MetaStruct {
> ```

I'm not a fan of naming a struct `Struct`. The only time I think that makes a lot of sense is if you are writing a compiler and your struct actually represent a struct in whatever you are compiling :)
___
*[nftnl/src/expr/meta.rs, line 95 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-em200fgmbaErxIVc:-M1-em212TzfpwCe3c2k:bo41675) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/meta.rs#L95)):*
> ```Rust
>     };
>     (@mark $(set)?) => {
>         $crate::expr::Meta::Mark
> ```

Is it *only* mark that can/should be used with `set_value: true`? Then why not have:
```rust
enum Meta {
    ....
    Mark(bool),
    ....
}
```
Instead of creating a new struct that wraps everything.

A goal is that this library should be possible to use cleanly without using the macros. The macros are helpers, but it should be fully possible (and good looking) to use the types directly.
___
*[nftnl/src/expr/verdict.rs, line 9 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-hQ0X1CYwm5bS1eO2:-M1-hQ0X1CYwm5bS1eO3:b-z1056z) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/verdict.rs#L9)):*
> ```Rust
> /// but here it's simplified to only represent a verdict.
> #[derive(Debug, Clone, Eq, PartialEq, Hash)]
> pub enum Verdict {
> ```

I'm thinking we should maybe keep this type in `immediate.rs`. So we still have a 1:1 mapping between `libnftnl` expressions and Rust modules. So one can look in a single place to see how we implement the `immediate` expression.


<!-- Sent from Reviewable.io -->

2020-02-26 10:10 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/24)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @faern)

___
*[nftnl/src/expr/ct.rs, line 16 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-fd4rBWkISRbJy9HB:-M1-u90T--3fGSkRDQ6M:bzgkvsh) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/ct.rs#L16)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Same feedback as on the `Meta` type. Can't we make the enum carry the `set_value` only in the variants where it makes sense? That is if only setting a value makes sense in a subset of the variants. If it's always valid to `set_value: true` my argument does not hold, but if so I think we should work on the structure here to make the wrapper `ConntrackStruct` the top level type and better named and have the variant be a sub-type.
</blockquote></details>

Done. Only `ct mark` can be set, I believe.
___
*[nftnl/src/expr/immediate.rs, line 6 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-h73p5eH5Bz4Crxpt:-M1-uUAUEeXw25eNnTbA:b-896fix) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/immediate.rs#L6)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Since on the `libnftnl` level a verdict is an immediate expression users might come to this module/type to find out how to do verdicts. If we keep them as separate types I think the documentation for the `Immediate` should say this and point to the docs for the `Verdict` type.
</blockquote></details>

Done.
___
*[nftnl/src/expr/immediate.rs, line 46 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-wNN-8mspSF0PQbs3:-M1-wNN-8mspSF0PQbs4:bj4uxvg) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/immediate.rs#L46)):*
> ```Rust
> macro_rules! nft_expr_immediate {
>     (data $value:expr) => {
>         $crate::expr::Immediate::Data($value)
> ```

The syntax here is `immediate data <value>`. I'm thinking it should be simply `immediate <value>`. That would be more consistent with the netlink instructions:

```
[ immediate reg 1 <value> ]
[ meta set mark with reg 1 ]
```
___
*[nftnl/src/expr/meta.rs, line 33 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-fCbX6boABwNGroR1:-M1-vQY85IKmp0o094tT:bss4a2b) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/meta.rs#L33)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm not a fan of naming a struct `Struct`. The only time I think that makes a lot of sense is if you are writing a compiler and your struct actually represent a struct in whatever you are compiling :)
</blockquote></details>

Removed.
___
*[nftnl/src/expr/meta.rs, line 95 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-em200fgmbaErxIVc:-M1-vU477wO9KLiBVOfo:b-v63oyh) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/meta.rs#L95)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Is it *only* mark that can/should be used with `set_value: true`? Then why not have:
```rust
enum Meta {
    ....
    Mark(bool),
    ....
}
```
Instead of creating a new struct that wraps everything.

A goal is that this library should be possible to use cleanly without using the macros. The macros are helpers, but it should be fully possible (and good looking) to use the types directly.
</blockquote></details>

Done. There are a few other options (https://wiki.nftables.org/wiki-nftables/index.php/Setting_packet_metainformation) that can be set, but this still seems simpler.
___
*[nftnl/src/expr/verdict.rs, line 9 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-hQ0X1CYwm5bS1eO2:-M1-yEzj8iOAkWz9mmzF:b-896fix) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/verdict.rs#L9)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I'm thinking we should maybe keep this type in `immediate.rs`. So we still have a 1:1 mapping between `libnftnl` expressions and Rust modules. So one can look in a single place to see how we implement the `immediate` expression.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-26 14:30 UTC, faern requested changes
> Reviewed 1 of 5 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/24)* status: all files reviewed, 6 unresolved discussions (waiting on @dlon)

___
*[nftnl/src/expr/ct.rs, line 16 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-fd4rBWkISRbJy9HB:-M10s4mVD_uYkiPSm79P:bp6nm32) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/ct.rs#L16)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Done. Only `ct mark` can be set, I believe.
</blockquote></details>

This is a great improvement :+1: However I have the same follow-up concern here as with `Meta`: It's hard to interpret what `Mark(true)` vs `Mark(false)` actually do. Implementing them with a named member or as separate enum variants will greatly help with that. And maybe an ounce of documentation.
___
*[nftnl/src/expr/ct.rs, line 51 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M10s_CvEdlfxsfHDfZl:-M10s_CvEdlfxsfHDfZm:b32ne1i) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/ct.rs#L51)):*
> ```Rust
>         $crate::expr::Conntrack::State
>     };
>     (mark set) => {
> ```

I know this can be perceived as a nitpick. But having the macro variants written in the same order as the enum variants can have a great impact on readability IMO.
___
*[nftnl/src/expr/immediate.rs, line 7 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M10sta99pYIRW9mtiAz:-M10sta99pYIRW9mtiB-:b-wvboym) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/immediate.rs#L7)):*
> ```Rust
> 
> /// An immediate expression.
> /// Verdicts are handled separately by the Verdict type.
> ```

If you just enclose Verdict in hard brackets, `[Verdict]`, it will be parsed as a link. And `rustdoc` will automatically see it's a local type, so it will create a link to the actual type. That will make the documentation easier to navigate.
___
*[nftnl/src/expr/immediate.rs, line 46 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-wNN-8mspSF0PQbs3:-M10tewv0-rcTQ4M5cmD:b7he3f) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/immediate.rs#L46)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

The syntax here is `immediate data <value>`. I'm thinking it should be simply `immediate <value>`. That would be more consistent with the netlink instructions:

```
[ immediate reg 1 <value> ]
[ meta set mark with reg 1 ]
```
</blockquote></details>

Currently `Immediate` only have a single variant. Is it likely it will have more? I have not checked what other stuff one can do with an immediate. If not, optimizing the macro to make the normal `Data` case easier to use does make sense, I agree.
___
*[nftnl/src/expr/meta.rs, line 10 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M10VqgWEV7aQPnGVh1f:-M10VqgWEV7aQPnGVh1g:bmr1ghx) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/meta.rs#L10)):*
> ```Rust
>     Cgroup,
>     /// Packet mark.
>     Mark(bool),
> ```

I find it hard to understand what this does without reading the implementation *and* a significant amount about `libnftnl`. A potential solution is two completely separate enum variants. `Mark` and `SetMark`. Since they do significantly different things. And they would need to be properly documented to show their difference.

If we want to keep it a single variant it can also be named with `Mark { set: bool },` to make it more clear, because then any user of this variant will type `Meta::Mark(set: true)` which is more understandable than just `Meta::Mark(true)`. But I think the separate variants way is the most understandable?
___
*[nftnl/src/expr/meta.rs, line 46 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M10W-949Mc7wdOoLdw4:-M10W-9577aduIfreWis:bv7kcxc) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/meta.rs#L46)):*
> ```Rust
>             IifType => libc::NFT_META_IIFTYPE as u32,
>             OifType => libc::NFT_META_OIFTYPE as u32,
>             Mark(_) => libc::NFT_META_MARK as u32,
> ```

Can we please keep the order of the match arms the same as the order the variants are declared in in the enum? That is IMO important for readability.

Regarding the sort order in the enum. I think I have used the same order there as the C header files used, but I can't remember exactly.

Same goes for order of macro variants.

Consistency is key :)


<!-- Sent from Reviewable.io -->

2020-02-26 16:08 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/24)* status: 1 of 4 files reviewed, 6 unresolved discussions (waiting on @faern)

___
*[nftnl/src/expr/ct.rs, line 16 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-fd4rBWkISRbJy9HB:-M11CeC0276h7t1BNblJ:bk1veid) ([raw file](https://github.com/mullvad/nftnl-rs/blob/744a4282d3fd6d3df7ba4351e6047c0e5598bb04/nftnl/src/expr/ct.rs#L16)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is a great improvement :+1: However I have the same follow-up concern here as with `Meta`: It's hard to interpret what `Mark(true)` vs `Mark(false)` actually do. Implementing them with a named member or as separate enum variants will greatly help with that. And maybe an ounce of documentation.
</blockquote></details>

Updated. It crossed my mind too, but I guess I figured it was clear enough.
___
*[nftnl/src/expr/ct.rs, line 51 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M10s_CvEdlfxsfHDfZl:-M11Cu-d1ALbgDQAbBNP:b-d88gch) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/ct.rs#L51)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I know this can be perceived as a nitpick. But having the macro variants written in the same order as the enum variants can have a great impact on readability IMO.
</blockquote></details>

Updated to use the same order as in the C header.
___
*[nftnl/src/expr/immediate.rs, line 7 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M10sta99pYIRW9mtiAz:-M11D4272iOUo16w3Wpl:b-896fix) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/immediate.rs#L7)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

If you just enclose Verdict in hard brackets, `[Verdict]`, it will be parsed as a link. And `rustdoc` will automatically see it's a local type, so it will create a link to the actual type. That will make the documentation easier to navigate.
</blockquote></details>

Done.
___
*[nftnl/src/expr/immediate.rs, line 46 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M1-wNN-8mspSF0PQbs3:-M11E8Fg2r4cJKQU5CKb:b-bulfli) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/immediate.rs#L46)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Currently `Immediate` only have a single variant. Is it likely it will have more? I have not checked what other stuff one can do with an immediate. If not, optimizing the macro to make the normal `Data` case easier to use does make sense, I agree.
</blockquote></details>

I'm not aware of any other use cases, but I'm not certain. Leaving `data` as is but simplifying the code somewhat.
___
*[nftnl/src/expr/meta.rs, line 10 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M10VqgWEV7aQPnGVh1f:-M11DrZU2Ycs4S7tpiVg:bp1x6u4) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/meta.rs#L10)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I find it hard to understand what this does without reading the implementation *and* a significant amount about `libnftnl`. A potential solution is two completely separate enum variants. `Mark` and `SetMark`. Since they do significantly different things. And they would need to be properly documented to show their difference.

If we want to keep it a single variant it can also be named with `Mark { set: bool },` to make it more clear, because then any user of this variant will type `Meta::Mark(set: true)` which is more understandable than just `Meta::Mark(true)`. But I think the separate variants way is the most understandable?
</blockquote></details>

Done: using `Mark { set: bool }`.
___
*[nftnl/src/expr/meta.rs, line 46 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M10W-949Mc7wdOoLdw4:-M11EuUaDmrpZRBATnZN:bf1mw0u) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/meta.rs#L46)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Can we please keep the order of the match arms the same as the order the variants are declared in in the enum? That is IMO important for readability.

Regarding the sort order in the enum. I think I have used the same order there as the C header files used, but I can't remember exactly.

Same goes for order of macro variants.

Consistency is key :)
</blockquote></details>

Good. I've updated it to consistently use the same order as the C header.


<!-- Sent from Reviewable.io -->

2020-02-27 07:43 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-:-M14tofw1jEucMtgujfC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[nftnl/src/expr/meta.rs, line 46 at r2](https://reviewable.io/reviews/mullvad/nftnl-rs/24#-M10W-949Mc7wdOoLdw4:-M14te-96SIs1r8sVxbc:bb6mt9b) ([raw file](https://github.com/mullvad/nftnl-rs/blob/a94eeb6185b44457ee2a06f665fbc9e274ccd700/nftnl/src/expr/meta.rs#L46)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Good. I've updated it to consistently use the same order as the C header.
</blockquote></details>

:+1:


<!-- Sent from Reviewable.io -->

2020-02-27 15:28 UTC, merged