Add base chain types
mullvad/nftnl-rs pull request #25
Opened 2020-02-27 15:45 UTC by dlon

In order to set packet marks, the base chain type must be set to [`route`](https://wiki.nftables.org/wiki-nftables/index.php/Configuring_chains) (rather than `filter`). This is done using `chain.set_base_type(type)`.

2020-02-27 15:51 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/25)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @faern)

___
*[nftnl/src/chain.rs, line 107 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/25#-M16KuTsDj9Wb_e8twFS:-M16KuTsDj9Wb_e8twFT:b2gyepw) ([raw file](https://github.com/mullvad/nftnl-rs/blob/4fe418db1ec7bd5251a6f0ba0806c50636ffab9b/nftnl/src/chain.rs#L107)):*
> ```Rust
>     /// Set the type of a base chain. This only applies if the chain is registered
>     /// with a hook by calling `set_hook`.
>     pub fn set_base_type(&mut self, chain_type: ChainType) {
> ```

It would make sense to add this parameter to `set_hook`. Is that a bad idea since it would break the existing interface?
___
*[nftnl/src/chain.rs, line 112 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/25#-M16Kben2ElhT5z2r31n:-M16Kben2ElhT5z2r31o:b-dei98l) ([raw file](https://github.com/mullvad/nftnl-rs/blob/4fe418db1ec7bd5251a6f0ba0806c50636ffab9b/nftnl/src/chain.rs#L112)):*
> ```Rust
>                 self.chain,
>                 sys::NFTNL_CHAIN_TYPE as u16,
>                 CString::new(chain_type.as_str()).unwrap().as_ptr()
> ```

These `CString`s could be static/const rather than allocated each time, I assume?


<!-- Sent from Reviewable.io -->

2020-02-27 16:16 UTC, faern requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/25)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[nftnl/src/chain.rs, line 38 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/25#-M16QLm78qFfl_1-ScMc:-M16QLm78qFfl_1-ScMd:b-bqlumi) ([raw file](https://github.com/mullvad/nftnl-rs/blob/4fe418db1ec7bd5251a6f0ba0806c50636ffab9b/nftnl/src/chain.rs#L38)):*
> ```Rust
> /// Base chain type.
> #[derive(Debug, Copy, Clone, Eq, PartialEq, Hash)]
> #[repr(u32)]
> ```

Why does it need a repr at all? I can't see anywhere where the variants are used as their integer representations, nor are they even assigned specific values right now :thinking: 
___
*[nftnl/src/chain.rs, line 41 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/25#-M16QUsE6-7ereK-Pz36:-M16QUsE6-7ereK-Pz37:bd9o2rr) ([raw file](https://github.com/mullvad/nftnl-rs/blob/4fe418db1ec7bd5251a6f0ba0806c50636ffab9b/nftnl/src/chain.rs#L41)):*
> ```Rust
> pub enum ChainType {
>     /// Used to filter packets.
>     /// Supported protocols: ip, ip6, inet, arp, and bridge tables.
> ```

Awesome that you added docs :+1:
___
*[nftnl/src/chain.rs, line 107 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/25#-M16KuTsDj9Wb_e8twFS:-M16Pj_m2ScC0MIcvxou:bkfc8d9) ([raw file](https://github.com/mullvad/nftnl-rs/blob/4fe418db1ec7bd5251a6f0ba0806c50636ffab9b/nftnl/src/chain.rs#L107)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

It would make sense to add this parameter to `set_hook`. Is that a bad idea since it would break the existing interface?
</blockquote></details>

Breaking the API is fine. It's a `0.x` crate anyway and not that many users (that we know of). And it's more important that the API is nice, ergonomic and understandable than API stability at this point IMO.
___
*[nftnl/src/chain.rs, line 112 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/25#-M16Kben2ElhT5z2r31n:-M16OQh635KZX41SOlVy:bjx2ok5) ([raw file](https://github.com/mullvad/nftnl-rs/blob/4fe418db1ec7bd5251a6f0ba0806c50636ffab9b/nftnl/src/chain.rs#L112)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

These `CString`s could be static/const rather than allocated each time, I assume?
</blockquote></details>

Yes. There is a lot of converting here that I hope should not be needed. Try something like:
```rust
impl ChainType {
    fn as_c_str(&self) -> &'static [u8] {
        match self {
            ChainType::A => b"aaa\0",
            ChainType::B => b"bbb\0",
        }
    }
}
```
And then avoid using `CString` and `unwrap()`s altogether?


<!-- Sent from Reviewable.io -->

2020-02-27 16:48 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/25)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faern)

___
*[nftnl/src/chain.rs, line 38 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/25#-M16QLm78qFfl_1-ScMc:-M16UlZ5CWI3uRvVQ2tm:bsabugo) ([raw file](https://github.com/mullvad/nftnl-rs/blob/4fe418db1ec7bd5251a6f0ba0806c50636ffab9b/nftnl/src/chain.rs#L38)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Why does it need a repr at all? I can't see anywhere where the variants are used as their integer representations, nor are they even assigned specific values right now :thinking: 
</blockquote></details>

Fixed. Initially, I had forgotten that this setting was a string.
___
*[nftnl/src/chain.rs, line 107 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/25#-M16KuTsDj9Wb_e8twFS:-M16V027DmlxRQj2eXqB:banyomk) ([raw file](https://github.com/mullvad/nftnl-rs/blob/4fe418db1ec7bd5251a6f0ba0806c50636ffab9b/nftnl/src/chain.rs#L107)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Breaking the API is fine. It's a `0.x` crate anyway and not that many users (that we know of). And it's more important that the API is nice, ergonomic and understandable than API stability at this point IMO.
</blockquote></details>

The type is a property of the (base) chain rather than the hook itself. Leaving it separate but renaming it to `set_type`.
___
*[nftnl/src/chain.rs, line 112 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/25#-M16Kben2ElhT5z2r31n:-M16WX0v7KGZF14mvToA:b-9755fa) ([raw file](https://github.com/mullvad/nftnl-rs/blob/4fe418db1ec7bd5251a6f0ba0806c50636ffab9b/nftnl/src/chain.rs#L112)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yes. There is a lot of converting here that I hope should not be needed. Try something like:
```rust
impl ChainType {
    fn as_c_str(&self) -> &'static [u8] {
        match self {
            ChainType::A => b"aaa\0",
            ChainType::B => b"bbb\0",
        }
    }
}
```
And then avoid using `CString` and `unwrap()`s altogether?
</blockquote></details>

Thank you.


<!-- Sent from Reviewable.io -->

2020-03-09 14:20 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/25#-:-M1zeib1BOOjIjimbct4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-03-10 09:11 UTC, merged