Fix flags and attributes
mullvad/nftnl-rs pull request #28
Opened 2020-03-30 20:19 UTC by dlon

One issue with older kernels stemmed from `NFTNL_CHAIN_FAMILY` not being set for chains. Some flags were updated as well.

Unrelatedly, add `Chain::dump` for producing a debug string representation of a chain.

2020-03-31 12:59 UTC, faern requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/28)* status: all files reviewed, 2 unresolved discussions (waiting on @dlon)

___
*[nftnl/src/chain.rs, line 122 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/28#-M3kbCnE0dfwg9arjMUI:-M3kbCnF6Hc0St5wCHDY:b-ltgtw1) ([raw file](https://github.com/mullvad/nftnl-rs/blob/07106c6d4c212a99954e35288e8fbc171fc85fbb/nftnl/src/chain.rs#L122)):*
> ```Rust
> 
>     /// Return a string representation of the chain.
>     pub fn dump(&self) -> CString {
> ```

It's a good idea to use the debug string functionality of `libnftnl`. But `nftnl` being a high level wrapper around `libnftnl` it's supposed to be Rust idiomatic rather than low level. As such I think it would be more correct to implement the `Debug` trait than to return a C string. So convert this method into an `impl fmt::Debug for Chain`?

I think it can use lossy conversion to avoid errors. It's after all just a debug representation.
___
*[nftnl/src/chain.rs, line 134 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/28#-M3ke40O4QVgjkVG3qPs:-M3ke40P-yCNM5NyHtGW:b3jxv2m) ([raw file](https://github.com/mullvad/nftnl-rs/blob/07106c6d4c212a99954e35288e8fbc171fc85fbb/nftnl/src/chain.rs#L134)):*
> ```Rust
>         }
>         let null_index = buffer.iter().position(|ch| *ch == b'\0').unwrap();
>         CString::new(&buffer[0..null_index]).unwrap()
> ```

Instead of manually finding the null byte you can use `CStr::from_ptr` (https://doc.rust-lang.org/stable/std/ffi/struct.CStr.html#method.from_ptr) that does that automatically. And then from the `CStr` to something that can be written in Rust: `CStr::to_string_lossy`.


<!-- Sent from Reviewable.io -->

2020-03-31 13:12 UTC, faern requested changes
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/28)* status: all files reviewed, 3 unresolved discussions (waiting on @dlon)

___
*[nftnl/src/chain.rs, line 129 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/28#-M3khhdT11c5ISHyIkDc:-M3khhdT11c5ISHyIkDd:b-fa97su) ([raw file](https://github.com/mullvad/nftnl-rs/blob/07106c6d4c212a99954e35288e8fbc171fc85fbb/nftnl/src/chain.rs#L129)):*
> ```Rust
>                 buffer.len(),
>                 self.chain,
>                 0,
> ```

This is the type argument. We should probably use the `nftnl_sys::NFTNL_OUTPUT_DEFAULT` constant instead of hardcoding this to an integer literal.


<!-- Sent from Reviewable.io -->

2020-04-01 09:57 UTC, dlon reviewed
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/28)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @faern)

___
*[nftnl/src/chain.rs, line 122 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/28#-M3kbCnE0dfwg9arjMUI:-M3pA3GX9DXTkfG4Nd0M:b-896fix) ([raw file](https://github.com/mullvad/nftnl-rs/blob/07106c6d4c212a99954e35288e8fbc171fc85fbb/nftnl/src/chain.rs#L122)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

It's a good idea to use the debug string functionality of `libnftnl`. But `nftnl` being a high level wrapper around `libnftnl` it's supposed to be Rust idiomatic rather than low level. As such I think it would be more correct to implement the `Debug` trait than to return a C string. So convert this method into an `impl fmt::Debug for Chain`?

I think it can use lossy conversion to avoid errors. It's after all just a debug representation.
</blockquote></details>

Done.
___
*[nftnl/src/chain.rs, line 129 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/28#-M3khhdT11c5ISHyIkDc:-M3pA4ON8Wg7Zmm9uM9s:b-896fix) ([raw file](https://github.com/mullvad/nftnl-rs/blob/07106c6d4c212a99954e35288e8fbc171fc85fbb/nftnl/src/chain.rs#L129)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

This is the type argument. We should probably use the `nftnl_sys::NFTNL_OUTPUT_DEFAULT` constant instead of hardcoding this to an integer literal.
</blockquote></details>

Done.
___
*[nftnl/src/chain.rs, line 134 at r1](https://reviewable.io/reviews/mullvad/nftnl-rs/28#-M3ke40O4QVgjkVG3qPs:-M3pA50B6VG4D9Juo2vL:b-896fix) ([raw file](https://github.com/mullvad/nftnl-rs/blob/07106c6d4c212a99954e35288e8fbc171fc85fbb/nftnl/src/chain.rs#L134)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Instead of manually finding the null byte you can use `CStr::from_ptr` (https://doc.rust-lang.org/stable/std/ffi/struct.CStr.html#method.from_ptr) that does that automatically. And then from the `CStr` to something that can be written in Rust: `CStr::to_string_lossy`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-04-01 10:58 UTC, faern approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/nftnl-rs/28#-:-M3pOBU-787exSkJuYBS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[nftnl/src/chain.rs, line 159 at r4](https://reviewable.io/reviews/mullvad/nftnl-rs/28#-M3pLhFUErcGWluU9BkD:-M3pLhFVB4HgooPBXcla:b-66fsia) ([raw file](https://github.com/mullvad/nftnl-rs/blob/508e1433dd6fa89efda815d7119a015c5178473f/nftnl/src/chain.rs#L159)):*
> ```Rust
>         }
>         let s = unsafe { CStr::from_ptr(buffer.as_ptr() as * const c_char) };
>         write!(fmt, "{:?}", s)
> ```

Great! :tada: 

Just nitpick:
I think clippy usually takes note of format strings that are just "{}" or "{:?}". They can be simplified to just something like `s.fmt(fmt)`.

This will also make our debug impl quote the `Chain` string with `"`s. Since the debug impl of `CStr` does that. I don't think that's a blocker. And I'm not sure what the best way around it would be either so probably keep that as is.


<!-- Sent from Reviewable.io -->

2020-04-01 14:58 UTC, merged